/**
 * Cart Recovery Cron — Sends abandoned cart emails
 * Ported from Ian's .cc: /api/cron/cart-recovery/
 *
 * Schedule: Every hour (configured in vercel.json)
 * Flow: Find abandoned carts → check delay thresholds → send recovery emails
 */
import { NextRequest, NextResponse } from "next/server";
import { timingSafeEqual } from "crypto";
import { prisma } from "@/server/trpc/trpc";

function verifyCronAuth(authHeader: string | null): boolean {
  const cronSecret = process.env.CRON_SECRET;
  if (!cronSecret) return false;
  if (!authHeader) return false;
  const token = authHeader.replace("Bearer ", "");
  if (token.length !== cronSecret.length) return false;
  return timingSafeEqual(Buffer.from(token), Buffer.from(cronSecret));
}

export async function GET(req: NextRequest) {
  // Verify cron secret (timing-safe)
  if (!verifyCronAuth(req.headers.get("authorization"))) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  try {
    // Get cart recovery settings
    const settings = await prisma.cartRecoverySettings.findFirst();
    if (!settings || !settings.isEnabled) {
      return NextResponse.json({ message: "Cart recovery disabled", processed: 0 });
    }

    // Find active abandoned carts
    const abandonedCarts = await prisma.abandonedCart.findMany({
      where: {
        status: "active",
        emailsSent: { lt: settings.maxEmailsPerCart },
        createdAt: {
          // Only carts created within the expiry window
          gte: new Date(Date.now() - settings.cartExpiryDays * 24 * 60 * 60 * 1000),
        },
      },
      include: { user: { select: { email: true, name: true } } },
      take: 50, // Process in batches
    });

    let emailsSent = 0;

    for (const cart of abandonedCarts) {
      const email = cart.email || cart.user?.email;
      if (!email) continue;

      // Determine which email to send (1, 2, or 3)
      const emailNumber = cart.emailsSent + 1;
      const cartAgeMinutes = (Date.now() - cart.createdAt.getTime()) / (1000 * 60);

      let delayMinutes: number;
      let discountPercent: number;
      let subject: string;
      let enabled: boolean;

      if (emailNumber === 1) {
        delayMinutes = settings.email1DelayMinutes;
        discountPercent = settings.email1DiscountPercent;
        subject = settings.email1Subject;
        enabled = settings.email1Enabled;
      } else if (emailNumber === 2) {
        delayMinutes = settings.email2DelayMinutes;
        discountPercent = settings.email2DiscountPercent;
        subject = settings.email2Subject;
        enabled = settings.email2Enabled;
      } else {
        delayMinutes = settings.email3DelayMinutes;
        discountPercent = settings.email3DiscountPercent;
        subject = settings.email3Subject;
        enabled = settings.email3Enabled;
      }

      if (!enabled || cartAgeMinutes < delayMinutes) continue;

      // Check if enough time has passed since last email
      if (cart.lastEmailSentAt) {
        const sinceLast = (Date.now() - cart.lastEmailSentAt.getTime()) / (1000 * 60);
        if (sinceLast < 60) continue; // At least 1 hour between emails
      }

      // Generate discount code if needed
      let discountCode: string | undefined;
      if (discountPercent > 0 && settings.autoGenerateDiscountCodes) {
        discountCode = `${settings.discountCodePrefix}-${cart.id}-${emailNumber}`;
        // Create coupon in DB
        await prisma.coupon.upsert({
          where: { code: discountCode },
          update: {},
          create: {
            code: discountCode,
            type: "PERCENTAGE",
            value: discountPercent,
            maxUses: 1,
            validUntil: new Date(Date.now() + settings.discountCodeExpiryHours * 60 * 60 * 1000),
          },
        });
      }

      // Send email via Resend (placeholder — uses existing email infrastructure)
      try {
        // TODO: Integrate with lib/email.ts sendCartRecoveryEmail()
        console.log(`[Cart Recovery] Would send email #${emailNumber} to ${email} for cart ${cart.id}`);

        // Record the email send
        await prisma.cartRecoveryEmail.create({
          data: {
            abandonedCartId: cart.id,
            userId: cart.userId,
            emailNumber,
            subject,
            recipientEmail: email,
            discountCode,
            discountPercent,
            cartTotal: cart.cartTotal,
            status: "sent",
          },
        });

        // Update abandoned cart
        await prisma.abandonedCart.update({
          where: { id: cart.id },
          data: {
            emailsSent: emailNumber,
            lastEmailSentAt: new Date(),
          },
        });

        emailsSent++;
      } catch (emailError) {
        console.error(`[Cart Recovery] Email send failed for cart ${cart.id}:`, emailError);
      }
    }

    // Expire old carts
    const expired = await prisma.abandonedCart.updateMany({
      where: {
        status: "active",
        createdAt: {
          lt: new Date(Date.now() - settings.cartExpiryDays * 24 * 60 * 60 * 1000),
        },
      },
      data: { status: "expired" },
    });

    return NextResponse.json({
      processed: abandonedCarts.length,
      emailsSent,
      expired: expired.count,
      timestamp: new Date().toISOString(),
    });
  } catch (error) {
    console.error("[Cart Recovery Cron] Error:", error);
    return NextResponse.json({ error: "Cron failed" }, { status: 500 });
  }
}
